ZSH_THEME="spaceship"

# === PROMPT ===
SPACESHIP_PROMPT_ADD_NEWLINE=false
# === CHAR ===
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SUFFIX=""
# === DIRECTORY ===
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_COLOR=86
# SPACESHIP_DIR_TRUNC_PREFIX="…/"
# === GIT BRANCH ===
SPACESHIP_GIT_BRANCH_COLOR=48
SPACESHIP_GIT_PREFIX="%F{15}on%f "
# === GIT STATUS ===
SPACESHIP_GIT_STATUS_COLOR="white"
SPACESHIP_GIT_STATUS_UNTRACKED="%F{161}?%F{white}"
SPACESHIP_GIT_STATUS_ADDED="%F{2}S%F{white}"
SPACESHIP_GIT_STATUS_MODIFIED="%F{214}M%F{white}"
SPACESHIP_GIT_STATUS_RENAMED="%F{41}»%F{white}"
SPACESHIP_GIT_STATUS_DELETED="%F{red}✘%F{white}"
SPACESHIP_GIT_STATUS_STASHED="%F{37}$%F{white}"
SPACESHIP_GIT_STATUS_UNMERGED="%F{166}=%F{white}"
SPACESHIP_GIT_STATUS_AHEAD="%F{226}⇡%F{white}"
SPACESHIP_GIT_STATUS_BEHIND="%F{226}⇣%F{white}"
SPACESHIP_GIT_STATUS_DIVERGED="%F{226}⇕%F{white}"
# === VI-MODE ===
SPACESHIP_VI_MODE_SHOW=false
