ZSH_THEME="spaceship"

# === PROMPT ===
SPACESHIP_PROMPT_ADD_NEWLINE=false
# === CHAR ===
SPACESHIP_CHAR_PREFIX="🚀 "
SPACESHIP_CHAR_SUFFIX=" "
# === DIRECTORY ===
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_COLOR=204
# === GIT BRANCH ===
SPACESHIP_GIT_BRANCH_COLOR=147
# === GIT STATUS ===
SPACESHIP_GIT_STATUS_COLOR="white"
SPACESHIP_GIT_STATUS_UNTRACKED="%F{red}?%F{white}"
SPACESHIP_GIT_STATUS_ADDED="%F{2}+%F{white}"
SPACESHIP_GIT_STATUS_MODIFIED="%F{214}!%F{white}"
# === VI-MODE ===
SPACESHIP_VI_MODE_SHOW=false
